# Generated by Django 3.2.4 on 2021-06-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dogs',
            new_name='Dog',
        ),
        migrations.RenameModel(
            old_name='Owners',
            new_name='Owner',
        ),
    ]
